mystr="Harry is a Programmer"
a=len(mystr)
print(mystr[0:a])
print(mystr[:a:2])
print(mystr[::-1])
print(mystr[-1])
print(mystr[-5:-3])
print(mystr.isalnum())
print(mystr.count("r"))
print(mystr.lower())
print(mystr.find("is"))
print(mystr.endswith("er"))
print(mystr.upper())
print(mystr.replace("is","are"))